### PR TITLE
Update press.html

### PR DESCRIPTION
**Pull request by intentiondesign**
Added realtor.com logo, moved Inc logo up to top line, and added latest publication to print interviews section

### CODE REVIEW

**Comment by intentiondesign** [comment]
what does merged mean?

[image: photo]
*RACHEL PRESTON PRINZ*
Founding Director, Archinia + Architecture for EveryBody

505-204-8177

www.archinia.com | www.architectureforeverybody.org
<http://twitter.com/Archinia> <http://www.facebook.com/ArchiniaDesign>
<http://www.linkedin.com/in/rachelprestonprinz/>
<http://www.instagram.com/archiniadesign>
<http://www.pinterest.com/archinia/pins/> <http://about.me/intention.design>
Get your own email signature
<https://www.wisestamp.com?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

**Comment by m2creates** [comment]
Your changes look perfect so I clicked "merge" to publish!

**Comment by intentiondesign** [comment]
weird, the changes arent showing up?

[image: photo]
*RACHEL PRESTON PRINZ*
Founding Director, Archinia + Architecture for EveryBody

505-204-8177

www.archinia.com | www.architectureforeverybody.org
<http://twitter.com/Archinia> <http://www.facebook.com/ArchiniaDesign>
<http://www.linkedin.com/in/rachelprestonprinz/>
<http://www.instagram.com/archiniadesign>
<http://www.pinterest.com/archinia/pins/> <http://about.me/intention.design>
Get your own email signature
<https://www.wisestamp.com?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

**Comment by m2creates** [comment]
Clear your cache on the page. I see your new talk and I think I see your
logo ordering change live.

**Comment by intentiondesign** [comment]
that did it. except the realtor.com logo isnt coming thru. I did something
wrong.

[image: photo]
*RACHEL PRESTON PRINZ*
Founding Director, Archinia + Architecture for EveryBody

505-204-8177

www.archinia.com | www.architectureforeverybody.org
<http://twitter.com/Archinia> <http://www.facebook.com/ArchiniaDesign>
<http://www.linkedin.com/in/rachelprestonprinz/>
<http://www.instagram.com/archiniadesign>
<http://www.pinterest.com/archinia/pins/> <http://about.me/intention.design>
Get your own email signature
<https://www.wisestamp.com?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

**Pull request merged**
